[package]
name = "check_docs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "check-docs"
path = "src/main.rs"

[dependencies]
cargo_metadata = "0.18"
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
syn = { version = "2", features = ["full", "parsing", "printing", "visit"] }
walkdir = "2"
